apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/created-by: email-controller
    app.kubernetes.io/part-of: email-controller
  name: email-controller-leader-election-rolebinding
  namespace: email-controller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: email-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: email-controller-system